# Generated by Django 3.2.18 on 2023-04-04 18:40

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Введите цветовой код в 16-ричном формате', max_length=7, validators=[recipes.validators.validate_tag_color], verbose_name='Цветовой hex-код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите slug', max_length=200, unique=True, validators=[recipes.validators.validate_tag_slug], verbose_name='slug'),
        ),
    ]
